### ISSUE TITLE
Cool project

### ISSUE THREAD

**Issue by shuvamgrad** [basic-bgnr/NepseUnofficialApi#1]
Will this application work for TMS?

**Comment by basic-bgnr** [comment]
> Will this application work for TMS?

I haven't looked too deeply into TMS. But I think TMS uses login cookies and websocket to communicate with server. Saying that, it won't be impossible but would require individual login credentials to get useful information out of it. Would look into it in my free time. Thanks

**Comment by robinnarsinghranabhat** [comment]
@basic-bgnr Do you plan on how we could further extend this for tms bot ? If you need help, I am more than ready. I just need guidance though !

**Comment by basic-bgnr** [comment]
TMS requires login cookies and theres always a possibility of nepse server logging user with usual request. Too risky....
