### ISSUE TITLE
cannot import name 'Nepse' error

### ISSUE THREAD

**Issue by surajrimal07** [basic-bgnr/NepseUnofficialApi#4]
Hello sir thank you for this project however I get following error when trying to run, any solution to this issue?

, C:\Users\Admin\Desktop\NepseAPI\example> python NepseServer.py
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\NepseAPI\example\NepseServer.py", line 5, in <module>
    from nepse import Nepse
ImportError: cannot import name 'Nepse' from 'nepse' (C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nepse\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\NepseAPI\example\NepseServer.py", line 10, in <module>
    from nepse import Nepse
ImportError: cannot import name 'Nepse' from 'nepse' (C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\nepse\__init__.py)

Thank you.

**Comment by basic-bgnr** [comment]
You need to run the example from the project root folder.
i.e.

C:\Users\Admin\Desktop\NepseAPI\python example\NepseServer.py
